pib/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^', include('homepage.urls')),
    url(r'^api/v1/', include('pib.urls_api', namespace='api')),
    url(r'^curriculum/', include('curricula.urls')),
    url(r'^editor/', include('editor.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^nested_admin/', include('nested_admin.urls')),
    url(r'^blog/', include('blog.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pib_auth/models.py
from django.db import models
from django.core import urlresolvers
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.base_user import BaseUserManager, AbstractBaseUser
from django.contrib.contenttypes.models import ContentType


class UserManager(BaseUserManager):

    def create(self, *args, **kwargs):
        user = super(UserManager, self).create(*args, **kwargs)
        return user

    def create_user(self, email, first_name=None, last_name=None, password=None):
        """
        Creates and saves a User with the given username, first_name,
        last_name, email and password.
        """
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            first_name=first_name,
            last_name=last_name,
            email=self.normalize_email(email),
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, first_name, last_name, password):
        """
        Creates and saves a User with the given username, first_name,
        last_name, email and password.
        """
        user = self.create_user(
            first_name=first_name,
            last_name=last_name,
            email=email,
            password=password,
        )
        user.is_superuser = True
        user.is_staff = True
        user.save(using=self._db)
        return user


class User(PermissionsMixin, AbstractBaseUser):
    """
    Custom Authentication User
    """

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    objects = UserManager()

    email = models.EmailField(max_length=255, unique=True)
    first_name = models.CharField(max_length=127, blank=True)
    last_name = models.CharField(max_length=127, blank=True)

    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)

    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def get_admin_url(self):
        content_type = ContentType.objects.get_for_model(self.__class__)
        return urlresolvers.reverse(
            'admin:{}_{}_change'.format(
                content_type.app_label,
                content_type.model
            ),
            args=[self.id]
        )

    @property
    def full_name(self):
        if self.first_name or self.last_name:
            return '{} {}'.format(self.first_name, self.last_name)
        else:
            return self.email

    def get_full_name(self):
        return self.full_name

    def get_short_name(self):
        return self.first_name or self.email

    def __str__(self):
        return '{} <{}>'.format(self.full_name, self.email)

profiles/models.py
from django.conf import settings
from django.db import models


class BaseModel(models.Model):

    class Meta:
        abstract = True

    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)


class Profile(BaseModel):

    class Meta:
        db_table = 'profiles_profiles'

    user = models.OneToOneField(settings.AUTH_USER_MODEL)
    sound_enabled = models.BooleanField(default=True)
    all_lessons_unlocked = models.BooleanField(default=False)

    def __str__(self):
        return 'Profile: {}'.format(self.user.email)

pib_auth/forms.py
from django import forms


class SignupForm(forms.Form):

    first_name = forms.CharField(max_length=30, label='First Name', required=False)
    last_name = forms.CharField(max_length=30, label='Last Name', required=False)

    def signup(self, request, user):
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.save()

profiles/views.py
from django.shortcuts import render

# Create your views here.

profiles/templates/profiles/profile_modal.html
{% load i18n %}
{% load static %}
{% load account socialaccount %}

{% get_providers as socialaccount_providers %}


<script type="text/javascript" src="{% static "pib_auth/js/modal.js" %}"></script>
{% if user.is_authenticated %}
    <div class="modal fade profile-modal" id="profile-modal" role="dialog">
        <div class="modal-dialog" role"document">
            <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Profile</h4>
            </div>
            <div class="modal-body">
            <div>
            <form action="{% url 'account_login' %}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="next" value="{{ redirect_to }}" />
                <div clas="form-group row">
                    <label for="id_first_name">First Name:</label>
                    <input name="first_name" type="text" class="form-control" id="id_first_name" placeholder="First" required>
                </div>
                <div clas="form-group row">
                    <label for="id_last_name">Password:</label>
                    <input name="last_name" type="text" class="form-control" id="id_last_name" placeholder="Last" required>
                </div>
                <div clas="form-group row">
                    <label for="id_remember">Remember Me:</label>
                    <input name="remember" type="checkbox" class="form-check" id="id_remember">
                </div>
                <input class="btn btn-primary" type="submit" value="Login"/>
		<a href="{% url 'account_reset_password' %}">Forgot Password?</a>
            </form>
            </div>
	    <div class="container">OR</div>
	    <div>
                <a title="{{socialaccount_providers.0.name}}" class="btn btn-outline-primary socialaccount_provider {{socialaccount_providers.0.id}} {{brand.id}}"
                        href="{% provider_login_url socialaccount_providers.0.id process=process scope=scope auth_params=auth_params %}">
                    {{ socialaccount_providers.0.name }}
                </a>
                /
                <a title="{{socialaccount_providers.1.name}}" class="btn btn-outline-primary socialaccount_provider {{socialaccount_providers.1.id}} {{brand.id}}"
                        href="{% provider_login_url socialaccount_providers.1.id process=process scope=scope auth_params=auth_params %}">
                    {{ socialaccount_providers.1.name }}
                </a>
            </div>

            </div>
            <div class="modal-footer">
                Don't have an account?
                <button class="btn btn-primary auth-modal-swap" data-toggle="modal">Signup &#62;&#62;</button>
            </div>
            </div>
        </div>
    </div>
    <div class="modal fade auth-modal" id="signup-modal" role="dialog">
        <div class="modal-dialog" role"document">
            <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Signup</h4>
            </div>
            <div class="modal-body">
            <div>
            <form action="{% url 'account_signup' %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="next" value="{{ redirect_to }}" />
                <div clas="form-group row">
                    <label for="id_firstname">First Name:</label>
                    <input name="first_name" type="text" class="form-control" id="id_firstname" placeholder="First" required>
                </div>
                <div clas="form-group row">
                    <label for="id_lastname">Last Name:</label>
                    <input name="last_name" type="text" class="form-control" id="id_lastname" placeholder="Last" required>
                </div>
                <div clas="form-group row">
                    <label for="id_username">Username:</label>
                    <input name="username" type="text" class="form-control" id="id_username" placeholder="username" required>
                </div>
                <div clas="form-group row">
                    <label for="id_email">E-mail:</label>
                    <input name="email" type="text" class="form-control" id="id_email" placeholder="e-mail address" required>
                </div>
                <div clas="form-group row">
                    <label for="id_password1">Password:</label>
                    <input name="password1" type="password" class="form-control" id="id_password1" placeholder="password" required>
                </div>
                <div clas="form-group row">
                    <label for="id_password2">Password (again):</label>
                    <input name="password2" type="password" class="form-control" id="id_password2" placeholder="password (again)" required>
                </div>
                <div clas="form-group row">
                    <label for="id_remember">Remember Me:</label>
                    <input name="remember" type="checkbox" class="form-check" id="id_remember">
                </div>
                <button class="btn btn-primary" type="submit">Signup</button>
            </form>
            </div>
	    <div class="container">OR</div>
	    <div>
                <a title="{{socialaccount_providers.0.name}}" class="btn btn-outline-primary socialaccount_provider {{socialaccount_providers.0.id}} {{brand.id}}"
                        href="{% provider_login_url socialaccount_providers.0.id process=process scope=scope auth_params=auth_params %}">
                    {{ socialaccount_providers.0.name }}
                </a>
                /
                <a title="{{socialaccount_providers.1.name}}" class="btn btn-outline-primary socialaccount_provider {{socialaccount_providers.1.id}} {{brand.id}}"
                        href="{% provider_login_url socialaccount_providers.1.id process=process scope=scope auth_params=auth_params %}">
                    {{ socialaccount_providers.1.name }}
                </a>
            </div>

            </div>
            <div class="modal-footer">
                Already have an account?
                <button class="btn btn-primary auth-modal-swap" data-toggle="modal">Login &#62;&#62;</button>
            </div>
            </div>
        </div>
    </div>
{% endif %}