blog/urls.py
from django.conf.urls import url
from . import views


app_name = 'blog'

urlpatterns = [
    url(r'^$', views.BlogHomepage, name='bloghomepage'),
    url(r'^collegescorecard-analysis/$', views.CollegeScorecard, name='collegescorecard-analysis'),
    url(r'^shankar/$', views.Shankar, name='shankar'),
    url(r'^collegescorecard/$', views.CollegeScorecardApp, name='collegescorecard'),
    url(r'^collegemap/$', views.CollegeMap, name='collegemap'),
]

homepage/urls.py
from django.conf.urls import url

from . import views


app_name = 'homepage'
urlpatterns = [
    url(r'^$', views.homepage, name='homepage'),
    url(r'^about/$', views.About, name='about'),
]

pib/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^', include('homepage.urls')),
    url(r'^api/v1/', include('pib.urls_api', namespace='api')),
    url(r'^curriculum/', include('curricula.urls')),
    url(r'^editor/', include('editor.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^nested_admin/', include('nested_admin.urls')),
    url(r'^blog/', include('blog.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

homepage/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

homepage/views.py
from django.shortcuts import render, redirect
from django.urls import reverse


def homepage(request):
    if request.user.is_authenticated():
        return redirect(reverse('curricula:curriculum'))
    return render(request, 'homepage/homepage.html')

def About(request):
    return render(request, 'homepage/about.html')

homepage/templates/homepage/about.html
{% extends "homepage/navbar.html" %}
{% load static %}

{% block ExtraHead %}
    <link rel="stylesheet" type="text/css" href="{% static 'homepage/style.css' %}" />
{% endblock %}

{% block content %}
    <div class="container">
        <div class = "border-bottom">
            <h1 class="blog-title">
                ABOUT US
            </h1>
        </div>
        <h2 style="text-align: center">
            Let’s be honest. Physics isn’t easy.
        </h2>
        <h3 style="text-align: center">
            Physics Is Beautiful is a free, interactive, easy way to learn physics for people of all backgrounds.
        </h3>
        <br>
        <p style="text-align: justify">
            Nicolas Scozzaro, Michael Darcy and Hiran Wijesinghe and are dedicated to making physics more interactive, accessible and fun.
            They have started "Physics is Beautiful," an app of gamified physics lessons that cover standard curriculum in an interactive way.
            Think of it like Duolingo or CodeAcademy but for physics.
        </p>
        <p style="text-align: justify">
            They are making physics more efficient and enjoyable by eliminating the dry textbooks and problem sets from the equation.
            With the $2000 in funding provided through winning a <a href="https://techhub.osu.edu/news/2016/11/16/and-grant-goes-2016-student-project-grant-winners">Tech Hub Tech Grant</a>, they are developing a web app that will offer free, quality physics instruction to be used in classes around the world.
        </p>
        <p style="text-align: justify">
            They built the initial site and implemented the platform as part of the homework in the summer intro physics course Physics 1200 at OSU during summer 2016.
            In early 2017 using the Tech Hub funding they hired Damian Hites to put the platform on a solid foundation.
            Damian is an experienced web developer who has worked for startups such as Rdio and MakeSpace, and he rebuilt the platform on a using a python web framework called Django and Facebook's front end library called React.js.
        </p>
        <p style="text-align: justify">
            Their ultimate goal is to enable people to learn physics in a fraction of the time than it takes today, and enjoy the learning process much more.
            Their aim is for their content to be thorough enough that students may eventually be able to pass the AP physics exam or even college courses by using only the app.
        </p>
        <p style="text-align: justify">
            The physics curriculum currently covers (listed in order) vectors, motion diagrams, position-, velocity- and acceleration versus time graphs, Newton's Laws, forces, and free-body diagrams.
            The structure is a series of lessons that consist of questions that build on one another, sometimes referred to as an "inductive-chain."
            After a few lessons learning new material, there are "game-review" lessons reviews the previous lessons in a game format which requires speed and accuracy to beat.
            They are dedicated to developing new lessons and improving current lessons, to allow people to learn physics as efficiently as possible.
        </p>
        <p style="text-align: justify">
            Physics is Beautiful was successfully used as part of the required homework in The Ohio State University's summer intro physics course (physics 1200) during the summer of 2016.
            It can also be used by high school physics teachers as a supplement for algebra & calculus-based physics (AP).
            Or it can be used just for fun!
        </p>
        <p stye="text-align: justify">
            We recently <a href="https://techhub.osu.edu/news/2017/07/27/physics-beautiful-app-released">opened Physics is Beautiful to the public</a>.
        </p>
    <div class="row">
    <div class="col-md-3">
      <div class="thumbnail">
        <a href="https://www.linkedin.com/in/nscozzaro" target="_blank">
          <img src="{% static 'homepage/images/about/nicolas.jpg' %}"  style="width:100%">
          <div class="caption">
            <p>Nicolas Scozzaro</p>
          </div>
        </a>
      </div>
    </div>
    <div class="col-md-3">
      <div class="thumbnail">
        <a href="https://www.linkedin.com/in/mike-darcy-610b6640/" target="_blank">
          <img src="{% static 'homepage/images/about/Darcy.jpg' %}"  style="width:100%">
          <div class="caption">
            <p>Michael Darcy</p>
          </div>
        </a>
      </div>
    </div>
        <div class="col-md-3">
      <div class="thumbnail">
        <a href="https://www.linkedin.com/in/webfarer/" target="_blank">
          <img src="{% static 'homepage/images/about/hiran.png' %}"  style="width:100%">
          <div class="caption">
            <p>Hiran Wijesinghe</p>
          </div>
        </a>
      </div>
    </div>
    <div class="col-md-3">
      <div class="thumbnail">
        <a href="https://www.linkedin.com/in/damianhites" target="_blank">
          <img src="{% static 'homepage/images/about/domhites.jpg' %}"  style="width:100%">
          <div class="caption">
            <p>Dom Hites</p>
          </div>
        </a>
      </div>
    </div>

  </div>
    </div>
{% endblock %}

homepage/templates/homepage/homepage.html
{% load static %}
{% load auth_tags %}

<head>
    <link rel="shortcut icon" type="image/png" href="{% static 'homepage/images/favicon/favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'homepage/main.css' %}">
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
    {#    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>#}
    {#    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>#}
    <title>Physics is Beautiful</title>
    <meta name="description" content="The free, interactive, easy way to learn physics for everyone. Full physics curriculum designed for all levels:
		algebra & calculus-based physics, AP, high-school & university, and for the casual learner" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="google-site-verification" content="NP7f-DpvWUhmilJHYIMqFthNKWFToSdt52-Z8W6CErc" />
    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-96737260-1', 'auto');
        ga('send', 'pageview');
    </script>
    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <script>
        (adsbygoogle = window.adsbygoogle || []).push({
            google_ad_client: "ca-pub-1780955227395785",
            enable_page_level_ads: true
        });
    </script>
</head>

<body>
<div id="front-page">
    <nav class="navbar navbar-expand-lg navbar-light">
        <button class="pull-right navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
                <li class="navbutton">
                    <a href="{% url 'homepage:about' %}" class="navlink">About Us</a>
                </li>
                <li class="navbutton">
                    <a href="{% url 'blog:bloghomepage' %}" class="navlink">Blog</a>
                </li>
                <li class="navbutton" id="loginButton" data-toggle="modal" data-target="#signup-modal">
                    <a href="#" class="navlink">Login / Signup</a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="jumbotron">
        <div class="container">
            <h1>Physics is <span style="white-space: nowrap;">beauti\(\!\int\!\)ul.</span></h1>
            <p>
                Start learning physics, free.
            </p>
            <button id="getStartedButton" class="d-block mx-auto" onclick="location.href='/curriculum/'">Get Started</button>
            <section>
                <a href="#" class="scroll-down" address="true"></a>
            </section>
        </div>
    </div>
</div>
<section class="ok">
    <div class="container-fluid" style="background: linear-gradient(white, #fbfbfb, white);">
        <div class="container-fluid mt-3 d-flex">
            <div class="card-deck" >
                <div class="card">
                    <a href="curriculum/lessons/4nXkRtEGMqGnNvcpLDfXmV" style="text-decoration: none !important">
                        <img class="card-img-top" src="{% static 'homepage/images/vectors.png' %}" alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-title">Vectors</h5>
                            <p class="card-text">Learn vectors by drawing them interactively</p>
                        </div>
                    </a>
                </div>
                <div class="card ">
                    <a href="curriculum/lessons/6imjwU5aXyfMvPZzCtz4FR" style="text-decoration: none !important">
                        <img class="card-img-top" src="{% static 'homepage/images/unit-conversion.png' %}" alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-title">Unit Conversion</h5>
                            <p class="card-text">Learn how to convert units, with automatic unit canceling. Get practice with prefixes (e.g. kilo, milli, centi) and convert between meters and feet, ounces and grams, and more.</p>
                        </div>
                    </a>
                </div>
                <div class="card">
                    <a href="curriculum/lessons/dNcLZmMkymPQ5TcqdmDAqT" style="text-decoration: none !important">
                        <img class="card-img-top" src="{% static 'homepage/images/graphs.png' %}" alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-title">Graphs</h5>
                            <p class="card-text">Improve your understanding of displacement, velocity, and acceleration graphs</p>
                        </div>
                    </a>
                </div>
                <div class="card">
                    <a href="curriculum/lessons/Zxk3SjzLAYtR4NxTUwxzJB" style="text-decoration: none !important">
                        <img class="card-img-top" src="{% static 'homepage/images/motion-diagrams.png' %}" alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-title">Motion diagrams</h5>
                            <p class="card-text">Learn the difference between position and displacement, speed vs velocity through freeze-frame motion diagrams</p>
                        </div>
                    </a>
                </div>
                <div class="card">
                    <a href="curriculum/lessons/hwJbeFd67Lk4H6LYW5aDg3" style="text-decoration: none !important">
                        <img class="card-img-top" src="{% static 'homepage/images/friction.png' %}" alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-title">Forces</h5>
                            <p class="card-text">Understand forces such as tension, friction, normal force, and practice drawing free-body diagrams interactively</p>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>
<div class="container-fluid" style="background: #f1f1f1">
    <div class="container mt-3">
        <footer class="pt-4 pt-md-5 border-top">
            <div class="row">
                <div class="col-12 col-md">
                    <img class="mb-2" src="{% static 'homepage/images/favicon/favicon-32x32.png' %}" alt="" width="24" height="24">
                    <small class="d-block mb-3 text-muted">© 2017-2018</small>
                </div>
                <div class="col-6 col-md">
                    <h5>Resources</h5>
                    <ul class="list-unstyled text-small">
                        <li><a class="text-muted" href="{% url 'blog:bloghomepage' %}">Blog</a></li>
                        <li><a class="text-muted" href="{% url 'blog:shankar' %}">Shankar</a></li>
                        <li><a class="text-muted" href="{% url 'blog:collegescorecard' %}">College scorecard</a></li>
                        <li><a class="text-muted" href="{% url 'blog:collegescorecard-analysis' %}">College analysis</a></li>
                    </ul>
                </div>
                <div class="col-6 col-md">
                    <h5>About</h5>
                    <ul class="list-unstyled text-small">
                        <li><a class="text-muted" href="{% url 'homepage:about' %}">Team</a></li>
                        <li><a class="text-muted" href="#">Locations</a></li>
                        <li><a class="text-muted" href="#">Privacy</a></li>
                        <li><a class="text-muted" href="#">Terms</a></li>
                    </ul>
                </div>
            </div>
        </footer>
    </div>
</div>



<script src="https://code.jquery.com/jquery-3.1.0.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script type="text/javascript">
    $(function() {
        $('.scroll-down').click (function() {
            $('html, body').animate({scrollTop: $('section.ok').offset().top }, 'slow');
            return false;
        });
    });
</script>
{% auth_modal user request.get_full_path %}
</body>

homepage/templates/homepage/navbar.html
{% load static %}

<head>
    <link rel="shortcut icon" type="image/png" href="{% static 'blog/images/favicon/favicon.ico' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'blog/navbar.css' %}" />

    {# Mathjax#}
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>

    {# JQuery #}
    <script src="{% static 'blog/jquery/jquery.min.js' %}"></script>

    {# Bootstrap CSS #}
    <link rel="stylesheet" href="{% static 'blog/bootstrap/bootstrap.min.css' %}" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    {# Bootstrap JS #}
    <script src="{% static 'blog/bootstrap/bootstrap.min.js' %}" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    {% block ExtraHead %} {% endblock %}
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-96737260-1', 'auto');
        ga('send', 'pageview');
    </script>
    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <script>
        (adsbygoogle = window.adsbygoogle || []).push({
            google_ad_client: "ca-pub-1780955227395785",
            enable_page_level_ads: true
        });
    </script>
</head>


<nav id="navTopOfScreen" class="navbar navbar-default navbar-static-top"><!-- navbar-fixed-top -->
    <div class="container-fluid">
        <div class="navbar-header">
            {# Physics is Beautiful logo #}
             {# Physics is Beautiful logo #}
            <a class="navbar-brand" href="/">
                <span class="nb-drop-level-1">
                    Physics is
                </span>
                <span style="white-space: nowrap;">
                    <span class="nb-drop-level-1"> beauti</span>\(\!\int\!\)<span class="nb-drop-level-1">ul.</span>
                </span>
            </a>
            {# Toggle which appears only on small screens/mobile with three icon-bar lines #}
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        {# Options which are displayed inline on the bar on desktop, or in the toggle menu for mobile #}
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'blog:bloghomepage' %}">Blog</a></li>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>

{% block content %} {% endblock %}