blog/urls.py
from django.conf.urls import url
from . import views


app_name = 'blog'

urlpatterns = [
    url(r'^$', views.BlogHomepage, name='bloghomepage'),
    url(r'^collegescorecard-analysis/$', views.CollegeScorecard, name='collegescorecard-analysis'),
    url(r'^shankar/$', views.Shankar, name='shankar'),
    url(r'^collegescorecard/$', views.CollegeScorecardApp, name='collegescorecard'),
    url(r'^collegemap/$', views.CollegeMap, name='collegemap'),
]

curricula/urls.py
from django.conf.urls import url

from . import views


app_name = 'curricula'

urlpatterns = [
    url(r'^((?P<uuid>[0-9a-zA-Z]+)/)?$', views.CurriculumView.as_view(), name='curriculum'),
    url(r'^modules/(?P<uuid>[0-9a-zA-Z]+)/$', views.CurriculumView.as_view(), name='module'),
    url(r'^lessons/(?P<uuid>[0-9a-zA-Z]+)/$', views.CurriculumView.as_view(), name='lesson'),
    url(r'^games/(?P<uuid>[a-z-]+)/$', views.CurriculumView.as_view(), name='game'),
]

pib/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^', include('homepage.urls')),
    url(r'^api/v1/', include('pib.urls_api', namespace='api')),
    url(r'^curriculum/', include('curricula.urls')),
    url(r'^editor/', include('editor.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^nested_admin/', include('nested_admin.urls')),
    url(r'^blog/', include('blog.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/views.py
from django.shortcuts import render
from blog.models import Collegescorecard
from django.http import HttpResponse
import pandas as pd
from bokeh.plotting import figure, ColumnDataSource
from bokeh.embed import components
from bokeh.models import HoverTool, CategoricalColorMapper, NumeralTickFormatter
import numpy as np

def BlogHomepage(request):
    return render(request, 'blog/blog_homepage.html')

def CollegeScorecard(request):
    return render(request, 'blog/collegescorecard-analysis.html')

def Shankar(request):
    return render(request, 'blog/shankar.html')

def CollegeMap(request):
    intensity_variable = 'tuitionfee_in'
    df = pd.DataFrame.from_records(
        Collegescorecard.objects.all().values('latitude','longitude',intensity_variable,
                                              ).filter(academicyear__in=[2014,]
                                                       ))
    df = df.convert_objects(convert_numeric=True)
    df= df.replace('', np.nan).dropna().reset_index(drop=True)
    df[intensity_variable]=df[intensity_variable]/df[intensity_variable].max()
    context={'addressPoints': df.values.tolist() }
    return render(request, 'blog/collegemap.html', context = context)

def CollegeScorecardApp(request):
    def load_data(years, x_axis, y_axis, selected_sectors, selected_institutions):
        # Axis dict provides a mapping of model name slug -> axis label
        # The extra "<1" in some columns represent fields that are less than one, for proper axis handling
        # The "$" is used for columns whose value are in dollars, for proper rendering in the tooltip
        axis_dict = {
            'adm_rate':['Admission rate', "<1"],
            'sat_avg': ['Average SAT equivalent score of students admitted'],
            'satvrmid':['Midpoint of SAT scores at the institution (critical reading)'],
            'satmtmid':['Midpoint of SAT scores at the institution (math)'],
            'satwrmid':['Midpoint of SAT scores at the institution (writing)'],
            'actcmmid':['Midpoint of the ACT cumulative score'],
            'actenmid':['Midpoint of the ACT English score'],
            'actmtmid':['Midpoint of the ACT math score'],
            'actwrmid':['Midpoint of the ACT writing score'],
            'ugds':['Undergraduate enrollment'],
            'ugds_white':['Percent of undergraduates who are white', '<1'],
            'ugds_black':['Percent of undergraduates who are black', '<1'],
            'ugds_hisp':['Percent of undergraduates who are hispanic', '<1'],
            'ugds_asian':['Percent of undergraduates who are asian', '<1'],
            'ugds_aian':['Percent of undergraduates who are American Indian/Alaska Native', '<1'],
            'ugds_nhpi':['Percent of undergraduates who are Native Hawaiian/Pacific Islander', '<1'],
            'ugds_2mor':['Percent of undergraduates who are two or more races','<1'],
            'ugds_nra':['Percent of undergraduates who are non-resident aliens','<1'],
            'ugds_men': ['Percent of undergraduates who are men','<1'],
            'ugds_women': ['Percent of undergraduates who are women','<1'],
            'pptug_ef':['Percent of undergraduates students who are part-time','<1'],
            'costt4_a':['Average cost of attendance'],
            'tuitionfee_in':['In-state tuition and fees', '$'],
            'tuitionfee_out':['Out-of-state tuition and fees','$'],
            'tuitfte':['Net tuition revenue per full-time equivalent student', '$'],
            'inexpfte':['Instructional expenditures per full-time equivalent student', '$'],
            'avgfacsal':['Average faculty salary', '$'],
            'pftfac':['Proportion of faculty that is full-time','<1'],
            'pctpell':['Percentage of undergraduates who receive a Pell Grant','<1'],
            'c150_4':['Completion rate at four-year institutions','<1'],
            'pctfloan':['Percent of all undergraduates receiving a federal student loan','<1'],
            'ug25abv':['Percentage of undergraduates aged 25 and above','<1'],
            'cdr3':['Three-year default rate'],
            'death_yr8_rt':['Percent died within 8 years at original institution','<1'],
            'comp_orig_yr8_rt':['Percent completed within 8 years at original institution','<1'],
            'compl_rpy_7yr_rt':['Seven-year repayment rate for completers'],
            'noncom_rpy_7yr_rt':['Seven-year repayment rate for non-completers'],
            'dep_inc_avg':['Average family income of dependent students in real 2015 dollars','$'],
            'ind_inc_avg':['Average family income of independent students in real 2015 dollars','$'],
            'debt_mdn':['Median debt upon entering repayment','$'],
            'grad_debt_mdn':['Median debt for students who have completed','$'],
            'wdraw_debt_mdn':['Median debt for students who have withdrawn','$'],
            'lo_inc_debt_mdn':['Median debt for students with family income between $0-$30,000'],
            'hi_inc_debt_mdn':['Median debt for students with family income $75,001+'],
            'dep_debt_mdn':['Median debt for dependent students'],
            'ind_debt_mdn':['Median debt for independent students'],
            'md_earn_wne_p10':['Median earnings of students 10 years after entry'],
            'sd_earn_wne_p10':['Standard deviation of earnings of students 10 years after entry'],
            'gt_25k_p10':['Percent of students earning over $25,000/year 10 years after entry','<1',],
            #'alias':['Institution alias'],
            #'academicyear':['Year'],
            # 'unitid': ['Institution ID'],
            # 'instnm': ['Institution name'],
            # 'city': ['City'],
            # 'stabbr':['State'],
            # 'zip':['Zip code'],
            # 'accredagency':['Accreditation agency'],
            # 'insturl':['Institution URL'],
            # 'npcurl':["URL for institution's net price calculator"],
            # 'sch_deg':['Predominant degree awarded'],
            # 'hcm2':['Schools that are on Heightened Cash Monitoring 2 by the Department of Education'],
            # 'main':['Flag for main campus'],
            # 'numbranch':['Number of branch campuses'],
            # 'preddeg':['Predominant undergraduate degree awarded'],
            # 'highdeg':['Highest degree awarded'],
            # 'control':['Control of institution'],
            # 'region':['Region'],
            # 'locale':['Locale'],
            # 'latitude':['Latitude'],
            # 'longitude':['Longitude'],
            # 'ccbasic':['Carnegie Classification -- basic'],
            # 'ccugprof':['Carnegie Classification -- undergraduate profile'],
            # 'ccsizset':['Carnegie Classification -- size and setting'],
            # 'hbcu':['Historically Black College and University'],
            # 'pbi':['Predominantly black institution'],
            # 'annhi':['Alaska Native Native Hawaiian serving institution'],
            # 'tribal':['Tribal college and university'],
            # 'aanapii':['Asian American Native American Pacific Islander-serving institution'],
            # 'hsi':['Hispanic-serving institution'],
            # 'nanti':['Native American non-tribal institution'],
            # 'menonlyv':['Men-only college'],
            # 'womenonly':['Women-only college'],
            # 'relaffil':['Religious affiliation'],
            # 'curroper':['Currently operating'],
            # 'npt4_pub':['Average net price for Title IV institutions (public institutions)'],
            # 'npt4_priv':['Average net price for Title IV institutions (private for-profit and nonprofit institutions)'],
            # 'npt41_pub':['Average net price for $0-$30,000 family income (public institutions)'],
            # 'npt45_pub':['Average net price for $110,000+ family income (public institutions)'],
            # 'npt41_priv':['Average net price for $0-$30,000 family income (private institutions)'],
            # 'npt45_priv':['Average net price for $110,000+ family income (private institutions)'],
            # 'npt4_048_pub':['Average net price for $0-$48,000 family income (public institutions)'],
            # 'npt4_048_priv':['Average net price for $0-$48,000 family income (private institutions)'],
            # 'num4_pub':['Number of Title IV students (public institutions)'],
            # 'num4_priv':['Number of Title IV students (private institutions)'],
            # 'num41_pub':['Number of Title IV students, $0-$30,000 family income (public institutions)'],
            # 'num45_pub':['Number of Title IV students, $110,000+ family income (public institutions)'],
            # 'num41_priv':['Number of Title IV students, $0-$30,000 family income (private institutions)'],
            # 'num45_priv':['Number of Title IV students, $110,000+ family income (private institutions)'],
            # 'c150_l4':['Completion rate at less-than-four-year institutions'],
            # 'ret_ft4':['Full-time retention rate at four-year institutions'],
            # 'ret_ftl4':['Full-time retention rate at less-than-four-year institutions'],
            # 'ret_pt4':['Part-time student retention rate at four-year institutions'],
            # 'ret_ptl4':['Part-time student retention rate at less-than-four-year institutions'],
            # 'costt4_p':['Average cost of attendance (program-year institutions)'],
        }
        sectors = ["Public 2-Year",
                   "Public 4-year",
                   "Private nonprofit 2-year",
                   "Private nonprofit 4-year",
                   "Private for-profit 2-year",
                   "Private for-profit 4-year",
                   ]
        year_list = map(str, reversed(range(1996,2015)))
        # Query database for data, and read it into a pandas dataframe
        df = pd.DataFrame.from_records(
            Collegescorecard.objects.all().values('academicyear',
                                                  x_axis,
                                                  y_axis,

blog/templates/blog/blog_homepage.html
{% extends "blog/navbar.html" %}
{% load static %}

{% block ExtraHead %}
    <link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}" />
{% endblock %}

{% block content %}
    <div class="container">
        <div class = "border-bottom">
            <h1 class="blog-title">
            <span class="nb-drop-level-1">
                    Physics is
                </span>
                <span style="white-space: nowrap;">
                    <span class="nb-drop-level-1"> beauti</span>\(\!\int\!\)<span class="nb-drop-level-1">ul blog.</span>
                </span>
            </h1>
        </div>
{#        <a href="{% url 'blog:college_scorecard' %}">#}
{#            <img src="{% static 'blog/images/college_scorecard/earnings_vs_debt/earnings_vs_debt.png' %}" class = "blog-entry-image"/>#}
{#        </a>#}
        <br>
        <a href = "{% url 'blog:collegescorecard' %}">
            <h2>College Scorecard Data Visualization App</h2>
        </a>
        By NICOLAS SCOZZARO - For my capstone project at <a href="https://www.thedataincubator.com/">The Data Incubator</a> I decided to create an app that enables easy visualization of the <a href = "https://collegescorecard.ed.gov/data/">College Scorecard data</a> (approximately 2 GB of data with 1745 columns) released by the Obama administration in late 2015. I have hand-selected 50 of the columns that I find most interesting and relevant. College debt and future earnings have a large impact on many peoples' lives, and my hope is that this app may help people to make more informed college choices by seeing how universities compare.
        <br>
        <a href="{% url 'blog:collegescorecard' %}">EXPLORE<span>»</span></a>

        <div class="article-date">April 18th, 2016</div>
        <a href = "{% url 'blog:collegescorecard-analysis' %}">
            <h2>Analysis of the College Scorecard data</h2>
        </a>
        In September of 2015, President Obama announced the release of data on all universities in the United States. The data includes "how much each school’s graduates earn, how much debt they graduate with, and what percentage of a school’s students can pay back their loans – which will help all of us see which schools do the best job of preparing America for success."
        <br>
        <a href="{% url 'blog:collegescorecard-analysis' %}">READ MORE <span>»</span></a>
        <div class="article-date">April 18th, 2016</div>
    </div>
{% endblock %}

blog/templates/blog/collegemap.html
{% load static %}
<html>
<head>
    <title>Leaflet.heat demo</title>
    <link rel="stylesheet" href="{% static 'blog/leaflet/leaflet.css' %}" />
    <script src="{% static 'blog/leaflet/leaflet.js' %}"></script>
    <style>
        #map { width: 800px; height: 600px; }
        body { font: 16px/1.4 "Helvetica Neue", Arial, sans-serif; }
        .ghbtns { position: relative; top: 4px; margin-left: 5px; }
        a { color: #0077ff; }
    </style>
</head>
<body>


<div id="map"></div>



<script src="{% static 'blog/leaflet/leaflet-heat.js' %}"></script>

<script>
    var addressPoints = {{ addressPoints | safe }};

    var map = L.map('map', {attributionControl: false}).setView(['39.8282', '-94.5795'], 4);

    var tiles = L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
        attribution: '<a href="http://osm.org/copyright">Nicolas Scozzaro</a>'
    }).addTo(map);

    addressPoints = addressPoints.map(function (p) { return [p[0], p[1]]; });

    var heat = L.heatLayer(addressPoints, {radius: 25, maxZoom:11, minOpacity:0}).addTo(map);

</script>
</body>
</html>

blog/templates/blog/collegescorecard.html
{% extends "blog/navbar.html" %}
{% load static %}
{% block ExtraHead %}
    <link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <link href="http://cdn.pydata.org/bokeh/release/bokeh-0.12.4.min.css" rel="stylesheet" type="text/css">
    <link href="http://cdn.pydata.org/bokeh/release/bokeh-widgets-0.12.4.min.css" rel="stylesheet" type="text/css">
    <script src="http://cdn.pydata.org/bokeh/release/bokeh-0.12.4.min.js"></script>
    <script src="http://cdn.pydata.org/bokeh/release/bokeh-widgets-0.12.4.min.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    {{ script | safe }}
    {% load static %}
    <script type = "text/javascript"  src="{% static 'blog/chosen_v1.6.2/chosen.jquery.min.js' %}" async></script>
    <link rel="stylesheet" href="{% static 'blog/chosen_v1.6.2/chosen.min.css' %}">
    <script type = "text/javascript"  src="{% static 'blog/js/nces.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="col-md-3">
            <form id='input' method='post' action='{% url 'blog:collegescorecard' %}' class="form-group">
                {% csrf_token %}
                <label for="yaxis">y-axis:</label>
                <select class="form-control" name = "yaxis" id="yaxis">
                    {% for key, value in axis_options.items|dictsort:0 %}
                        <option value = "{{ key }}"
                                {% if key == selected.y_axis %}
                                selected
                                {% endif %}
                        >{{ value.0 }}</option>
                    {% endfor %}
                </select>
                <label for="xaxis">x-axis:</label>
                <select class="form-control" name = "xaxis" id="xaxis">
                    {% for key, value in axis_options.items|dictsort:0%}
                        <option value = "{{ key }}"
                                {% if key == selected.x_axis %}
                                selected
                                {% endif %}
                        >{{ value.0 }}</option>
                    {% endfor %}
                </select>
                <br>
                <label for="years">Year(s):</label>
                <select multiple class="form-control" name = "years" id="years">
                    {% for year in year_list %}
                        <option {% if year in selected.years %}selected{% endif %}>{{ year }}</option>
                    {% endfor %}
                </select>
                <br>
                Sectors
                {% for sector in sector_list %}
                    <div class="checkbox">
                        <label>
                            <input
                                    type="checkbox"
                                    name = "sectors"
                                    id = "sectors"
                                    value="{{ sector }}"
                                    {% if sector in selected.sectors %} checked {% endif %}
                            >
                            {{ sector }}
                        </label>
                    </div>
                {% endfor %}
                <label for="institutions">Add universities to highlight:</label>
                <select multiple class="form-control chosen" name = "institutions" id = "institutions" >
                    {% for institution in institutions %}
                        <option {% if institution in selected.institutions %}selected{% endif %}>{{ institution }}</option>
                    {% endfor %}
                </select>
                <input type="submit" class="btn btn-default" value="Submit">
            </form>
        </div>
        <div class="col-md-9">
            {{ div | safe }}
        </div>
        <div class="col-md-12"> By <a href="https://www.linkedin.com/in/nscozzaro">NICOLAS SCOZZARO</a> - For my capstone project at <a href="https://www.thedataincubator.com/">The Data Incubator</a> I decided to create an app that enables easy visualization of the <a href = "https://collegescorecard.ed.gov/data/">College Scorecard data</a> (approximately 2 GB of data with 1745 columns) <a href="https://youtu.be/Tpaj9Sm7i7I">released by the Obama administration</a> in late 2015. I have hand-selected 50 of the columns that I find most interesting and relevant. College debt and future earnings have a large impact on many peoples' lives, and my hope is that this app may help people to make more informed college choices by seeing how universities compare.<br>
        If you have questions or comments, please reach out to me at nscozzaro@gmail.com.</div>
    </div>
{% endblock %}

blog/templates/blog/graph.html
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <link href="http://cdn.pydata.org/bokeh/release/bokeh-0.12.4.min.css" rel="stylesheet" type="text/css">
    <link href="http://cdn.pydata.org/bokeh/release/bokeh-widgets-0.12.4.min.css" rel="stylesheet" type="text/css">
    <script src="http://cdn.pydata.org/bokeh/release/bokeh-0.12.5.min.js"></script>
    <script src="http://cdn.pydata.org/bokeh/release/bokeh-widgets-0.12.5.min.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    {{ script | safe }}
    {% load static %}
    <script type = "text/javascript"  src="{% static 'blog/chosen_v1.6.2/chosen.jquery.min.js' %}" async></script>
    <link rel="stylesheet" href="{% static 'blog/chosen_v1.6.2/chosen.min.css' %}">
    <script type = "text/javascript"  src="{% static 'blog/js/nces.js' %}"></script>
</head>

<body>
<form id='input' method='post' action='{% url 'blog:graph' %}' class="form-group">
    {% csrf_token %}
    <label for="yaxis">y-axis:</label>
    <select class="form-control" name = "yaxis" id="yaxis">
        {% for key, value in axis_options.items|dictsort:0 %}
            <option value = "{{ key }}"
                    {% if key == selected.y_axis %}
                    selected
                    {% endif %}
            >{{ value.0 }}</option>
        {% endfor %}
    </select>
    <label for="xaxis">x-axis:</label>
    <select class="form-control" name = "xaxis" id="xaxis">
        {% for key, value in axis_options.items|dictsort:0%}
            <option value = "{{ key }}"
                    {% if key == selected.x_axis %}
                    selected
                    {% endif %}
            >{{ value.0 }}</option>
        {% endfor %}
    </select>
    <br>
    <label for="years">Year(s):</label>
    <select multiple class="form-control" name = "years" id="years">
        {% for year in year_list %}
            <option {% if year in selected.years %}selected{% endif %}>{{ year }}</option>
        {% endfor %}
    </select>
    <br>
    Sectors
    {% for sector in sector_list %}
        <div class="checkbox">
            <label>
                <input
                        type="checkbox"
                        name = "sectors"
                        id = "sectors"
                        value="{{ sector }}"
                        {% if sector in selected.sectors %} checked {% endif %}
                >
                {{ sector }}
            </label>
        </div>
    {% endfor %}
    <label for="institutions">Add universities to highlight:</label>
    <select multiple class="form-control chosen" name = "institutions" id = "institutions" >
        {% for institution in institutions %}
            <option {% if institution in selected.institutions %}selected{% endif %}>{{ institution }}</option>
        {% endfor %}
    </select>
    <input type="submit" class="btn btn-default" value="Submit">
</form>
<div>
    {{ div | safe }}
</div>
</body>

blog/templates/blog/navbar.html
{% load static %}

<head>
    <link rel="shortcut icon" type="image/png" href="{% static 'blog/images/favicon/favicon.ico' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'blog/navbar.css' %}" />

    {# Mathjax#}
    <script type="text/javascript" src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>

    {# JQuery #}
    <script src="{% static 'blog/jquery/jquery.min.js' %}"></script>

    {# Bootstrap CSS #}
    <link rel="stylesheet" href="{% static 'blog/bootstrap/bootstrap.min.css' %}" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    {# Bootstrap JS #}
    <script src="{% static 'blog/bootstrap/bootstrap.min.js' %}" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    {% block ExtraHead %} {% endblock %}
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-96737260-1', 'auto');
        ga('send', 'pageview');
    </script>
    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <script>
        (adsbygoogle = window.adsbygoogle || []).push({
            google_ad_client: "ca-pub-1780955227395785",
            enable_page_level_ads: true
        });
    </script>
</head>


<nav id="navTopOfScreen" class="navbar navbar-default navbar-static-top"><!-- navbar-fixed-top -->
    <div class="container-fluid">
        <div class="navbar-header">
            {# Physics is Beautiful logo #}
            <a class="navbar-brand" href="{% url 'blog:bloghomepage'  %}">
                <span class="nb-drop-level-1">
                    Physics is
                </span>
                <span style="white-space: nowrap;">
                    <span class="nb-drop-level-1"> beauti</span>\(\!\int\!\)<span class="nb-drop-level-1">ul blog.</span>
                </span>
            </a>
            {# Toggle which appears only on small screens/mobile with three icon-bar lines #}
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        {# Options which are displayed inline on the bar on desktop, or in the toggle menu for mobile #}
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'blog:bloghomepage' %}">Blog</a></li>
                <li><a href="{% url 'curricula:curriculum' %}">
                    <span class="nb-drop-level-1">
                        Physics is
                    </span>
                    <span class="nb-drop-level-1"> beauti</span>\(\!\int\!\)<span class="nb-drop-level-1">ul App</span>
                    </span></a></li>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>

{% block content %} {% endblock %}